
research-dashboard-presentation-slideshow.pdf: research-dashboard-presentation-slideshow.md
	pandoc -t beamer -i research-dashboard-presentation-slideshow.md -o research-dashboard-presentation-slideshow.pdf

clean:
	rm research-dashboard-presentation-slideshow.pdf
